# Generated by Django 3.2.3 on 2021-06-23 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('hi-sw', 'hi-sw'), ('club', 'club')], max_length=300)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('team', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=50)),
                ('introduction', models.FileField(upload_to='introductions/')),
                ('demo', models.FileField(upload_to='demos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
