# Generated by Django 3.2.3 on 2021-05-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideathon', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='mediafile',
            field=models.FileField(blank=True, upload_to='mediafiles/'),
        ),
    ]
