# Generated by Django 3.2.3 on 2021-05-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideathon', '0003_auto_20210517_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mediafile',
            field=models.FileField(blank=True, null=True, upload_to='mediafiles/'),
        ),
    ]
