# Generated by Django 3.2.3 on 2021-05-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideathon', '0006_alter_post_writer'),
        ('ideathon', '0009_alter_comment_content'),
    ]

    operations = [
    ]
