# Generated by Django 3.2.3 on 2021-05-22 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideathon', '0010_merge_20210521_1803'),
        ('ideathon', '0010_merge_20210521_1813'),
    ]

    operations = [
    ]
