# Generated by Django 3.2.3 on 2021-05-22 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideathon', '0010_merge_20210521_1711'),
        ('ideathon', '0011_merge_20210522_0341'),
    ]

    operations = [
    ]
